trigi.lisp (cl:asinh most-positive-double-float) does not work in several Lisp's.
Use the 'workaround' (just the constant) not only for Clisp, but
for all Lisp versions. It does also cause problems with sbcl/wine
when crosscompiling a Windows installer.

Some examples (GCL, CLISP from Ubuntu 20.04):

$ gcl
GCL (GNU Common Lisp)  2.6.12 CLtL1    Fri Apr 22 15:51:11 UTC 2016
[...]
>(cl:asinh  most-positive-double-float)

Error: ERROR "Can't print a non-number."

$ clisp
[...]
Welcome to GNU CLISP 2.49.92 (2018-02-18) <http://clisp.org/>
[1]> (cl:asinh  most-positive-double-float)

*** - ASINH: floating point overflow

$ java -jar abcl-bin-1.8.0/abcl.jar
Armed Bear Common Lisp 1.8.0
Java 11.0.13 Ubuntu
[...]
CL-USER(1): (cl:asinh  most-positive-double-float)
Output: #.DOUBLE-FLOAT-POSITIVE-INFINITY